/**
 *
 * Copyright (c) 2010, Joachim Draeger, Jon Herrmann, Simon Müller
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     * Neither the name of JAXBiS nor the names of its contributors may
 *       be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */



package com.googlecode.jaxbis.example2;

import com.googlecode.jaxbis.crypt.KeyRing;

import com.googlecode.jaxbis.api.SecuredObject;

/*
 * JAXBIS AUTOGENERATED CLASS
 */

public class SecuredAddress2 implements SecuredObject<Address2> {
    
    private java.lang.String postalCode;
    
    public void setPostalCode(
        final java.lang.String postalCode) {
        this.postalCode = postalCode;
    }
    
    public java.lang.String getPostalCode() {
        return postalCode;
    }
    
    private java.lang.String street;
    
    public void setStreet(
        final java.lang.String street) {
        this.street = street;
    }
    
    public java.lang.String getStreet() {
        return street;
    }
    
    private java.lang.String state;
    
    public void setState(
        final java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    private java.lang.String country;
    
    public void setCountry(
        final java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    private java.lang.String city;
    
    public void setCity(
        final java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getCity() {
        return city;
    }
    @Override
    public Address2 getPlainInstance(final KeyRing keyRing) {
        
        final Address2 decrpytedObject = new Address2();


        decrpytedObject.setPostalCode(getPostalCode());
        decrpytedObject.setStreet(getStreet());
        decrpytedObject.setState(getState());
        decrpytedObject.setCountry(getCountry());
        decrpytedObject.setCity(getCity());

    



        
        return decrpytedObject;
    }
}
