/**
 *
 * Copyright (c) 2010, Joachim Draeger, Jon Herrmann, Simon Müller
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     * Neither the name of JAXBiS nor the names of its contributors may
 *       be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */



package com.googlecode.jaxbis.example;

import com.googlecode.jaxbis.crypt.KeyRing;

import com.googlecode.jaxbis.api.SecuredMember;
import com.googlecode.jaxbis.api.SecurityType;
import com.googlecode.jaxbis.api.SecuredObject;
import com.googlecode.jaxbis.crypt.PlainInstanceBuilder;

/*
 * JAXBIS AUTOGENERATED CLASS
 */

public class SecuredPosition1 implements SecuredObject<Position1> {
    
    private java.lang.String title;
    
    public void setTitle(
        final java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    private SecuredMember securedSalaryRange;
    
    public void setSecuredSalaryRange(
        final SecuredMember securedSalaryRange) {
        this.securedSalaryRange = securedSalaryRange;
    }
    
    public SecuredMember getSecuredSalaryRange() {
        return securedSalaryRange;
    }
    @Override
    public Position1 getPlainInstance(final KeyRing keyRing) {
        
        final Position1 decrpytedObject = new Position1();

        final PlainInstanceBuilder plainInstanceBuilder = 
            new PlainInstanceBuilder(keyRing);

        decrpytedObject.setTitle(getTitle());

    


        decrpytedObject.setSalaryRange(
            plainInstanceBuilder.createPlainInstanceRecursive(
                getSecuredSalaryRange(),
                com.googlecode.jaxbis.example.SecuredSalaryRange1.class,
                SecurityType.ENCRYPTION)
        );                

        
        return decrpytedObject;
    }
}
