/**
 *
 * Copyright (c) 2010, Joachim Draeger, Jon Herrmann, Simon Müller
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     * Neither the name of JAXBiS nor the names of its contributors may
 *       be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.googlecode.jaxbis.integr.shop;

import com.googlecode.jaxbis.crypt.KeyRing;

import com.googlecode.jaxbis.api.SecuredMember;
import com.googlecode.jaxbis.api.SecurityType;
import com.googlecode.jaxbis.api.SecuredObject;
import com.googlecode.jaxbis.crypt.PlainInstanceBuilder;

/*
 * JAXBIS AUTOGENERATED CLASS
 * TODO: Auto-generated class stub
 */

public class SecuredTransaction implements SecuredObject<Transaction> {
    
    private java.math.BigDecimal amount;
    
    public void setAmount(
        final java.math.BigDecimal amount) {
        this.amount = amount;
    }
    
    public java.math.BigDecimal getAmount() {
        return amount;
    }
    
    private java.lang.String accountNumber;
    
    public void setAccountNumber(
        final java.lang.String accountNumber) {
        this.accountNumber = accountNumber;
    }
    
    public java.lang.String getAccountNumber() {
        return accountNumber;
    }
    private SecuredMember securedCreditCardNo;
    
    public void setSecuredCreditCardNo(
        final SecuredMember securedCreditCardNo) {
        this.securedCreditCardNo = securedCreditCardNo;
    }
    
    public SecuredMember getSecuredCreditCardNo() {
        return securedCreditCardNo;
    }

    @Override
    public Transaction getPlainInstance(final KeyRing keyRing) {
        
        final Transaction decrpytedObject = new Transaction();

        final PlainInstanceBuilder plainInstanceBuilder = 
            new PlainInstanceBuilder(keyRing);

        decrpytedObject.setAmount(getAmount());
        decrpytedObject.setAccountNumber(getAccountNumber());

    
        decrpytedObject.setCreditCardNo(
            plainInstanceBuilder.createPlainInstance(
                getSecuredCreditCardNo(),
                java.lang.String.class,
                SecurityType.ENCRYPTION)
        );



        
        return decrpytedObject;
    }
}
